name: CI
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build source code
        run: |
          npm i
          npm run build
      - name: Deploy to Firebase
        run: |
          npm i firebase-tools
          ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project codesupport-development