name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Runs Tests
        run: |
          npm i
          CI=true npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Builds the React App
        run: |
          npm i
          npm run build